name: SolveRift
description: "Mathematical Calculation App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  math_keyboard: ^0.2.1
  image_picker: ^1.0.7
  image_cropper: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  fonts:
    - family: CustomKeyIcons
      fonts:
        - asset: fonts/CustomKeyIcons.ttf

  assets:
    - img/logo.png